name: CI build

concurrency:
  group: ci
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java-version: [ 8.0.352+8, 11.0.17+8 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Build
        run: ./mvnw clean package -DskipTests=true

      - name: Test
        run: ./mvnw verify
